<?php
// =========================================
// THONG DONG - DATA (DEMO, NO DB)
// - Dùng chung cho shop.php, product-detail.php, cart, checkout...
// - Fix lỗi thiếu key: tag / size / burn
// =========================================

// ---------- Helpers ----------
function formatVND(int $n): string {
  return number_format($n, 0, ',', '.') . 'đ';
}

function findProductById($id, array $products): ?array {
  foreach ($products as $p) {
    if ((string)$p['id'] === (string)$id) return $p;
  }
  return null;
}

// ---------- Categories (9 danh mục) ----------
$CATEGORIES = [
  'nen_thom'     => 'Nến Thơm',
  'le_hoi'       => 'Bộ sưu tập mùa Lễ Hội',
  'nen_trang_tri'=> 'Nến Trang Trí',
  'td_phong'     => 'Tinh Dầu Thơm Phòng',
  'que_khuech_tan'=> 'Que Khuếch Tán Tinh Dầu',
  'may_khuech_tan'=> 'Máy Khuếch Tán Tinh Dầu',
  'td_treo'      => 'Tinh Dầu Treo',
  'phu_kien'     => 'Phụ kiện nến',
  'set_qua'      => 'Set quà tặng',
];

// ---------- Products (18 sp) ----------
$PRODUCTS = [
  [
    'id' => 1,
    'name' => 'Nến Thơm Đà Lạt (Pine & Wood)',
    'type' => 'Nến Thơm',
    'cat'  => 'nen_thom',
    'tag'  => $CATEGORIES['nen_thom'],
    'price'=> 150000,
    'desc' => 'Hương gỗ thông và sương sớm, mang lại cảm giác se lạnh của Đà Lạt',
    'status' => 'Đang bán',
    'size' => '200g',
    'burn' => '30–35 giờ',
    'image' => '/thongdong/assets/img/products/da-lat.png',
  ],
  [
    'id' => 2,
    'name' => 'Nến Thơm Good Morning',
    'type' => 'Nến Thơm',
    'cat'  => 'nen_thom',
    'tag'  => $CATEGORIES['nen_thom'],
    'price'=> 150000,
    'desc' => 'Hương cam chanh và bạc hà giúp tỉnh táo buổi sáng',
    'status' => 'Đang bán',
    'size' => '200g',
    'burn' => '30–35 giờ',
    'image' => '/thongdong/assets/img/products/good-morning.png',
  ],
  [
    'id' => 3,
    'name' => 'Nến Thơm Lavender Garden',
    'type' => 'Nến Thơm',
    'cat'  => 'nen_thom',
    'tag'  => $CATEGORIES['nen_thom'],
    'price'=> 180000,
    'desc' => 'Hương hoa oải hương thư giãn, hỗ trợ giấc ngủ',
    'status' => 'Đang bán',
    'size' => '220g',
    'burn' => '35–40 giờ',
    'image' => '/thongdong/assets/img/products/lavender-garden.png',
  ],
  [
    'id' => 4,
    'name' => 'Nến Thơm "Tết Sum Vầy"',
    'type' => 'Bộ sưu tập mùa Lễ Hội',
    'cat'  => 'le_hoi',
    'tag'  => $CATEGORIES['le_hoi'],
    'price'=> 250000,
    'desc' => 'Hương trầm hương và hoa mai, ấm áp không khí Tết cổ truyền',
    'status' => 'Đang bán',
    'size' => '250g',
    'burn' => '40–45 giờ',
    'image' => '/thongdong/assets/img/products/tet-sum-vay.png',

  ],
  [
    'id' => 5,
    'name' => 'Nến Tạo Hình Bánh Chưng',
    'type' => 'Bộ sưu tập mùa Lễ Hội',
    'cat'  => 'le_hoi',
    'tag'  => $CATEGORIES['le_hoi'],
    'price'=> 120000,
    'desc' => 'Nến trang trí hình bánh chưng xanh, hương lá nếp',
    'status' => 'Đang bán',
    'size' => '1 cái',
    'burn' => '8–10 giờ',
      'image' => '/thongdong/assets/img/products/banh-chung.png',
    
  ],
  [
    'id' => 6,
    'name' => 'Nến Tạo Hình Quả Quýt Tài Lộc',
    'type' => 'Bộ sưu tập mùa Lễ Hội',
    'cat'  => 'le_hoi',
    'tag'  => $CATEGORIES['le_hoi'],
    'price'=> 90000,
    'desc' => 'Nến hình quả quýt vàng ươm, hương vỏ quýt thơm mát',
    'status' => 'Đang bán',
    'size' => '1 cái',
    'burn' => '6–8 giờ',
      'image' => '/thongdong/assets/img/products/quyt.png',
  ],
  [
    'id' => 7,
    'name' => 'Set Quà Tết "Phú Quý"',
    'type' => 'Bộ sưu tập mùa Lễ Hội',
    'cat'  => 'le_hoi',
    'tag'  => $CATEGORIES['le_hoi'],
    'price'=> 550000,
    'desc' => 'Hộp quà sơn mài gồm nến mùi Trầm và tinh dầu Mùi Già',
    'status' => 'Đang bán',
    'size' => 'Set',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/tet-phu-quy.png',
  ],
  [
    'id' => 8,
    'name' => 'Tinh Dầu Sả Chanh (Lemongrass)',
    'type' => 'Tinh Dầu Thơm Phòng',
    'cat'  => 'td_phong',
    'tag'  => $CATEGORIES['td_phong'],
    'price'=> 85000,
    'desc' => 'Khử mùi, đuổi muỗi, tạo không gian sạch sẽ',
    'status' => 'Đang bán',
    'size' => '10ml',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/sa-chanh.png',
  ],
  [
    'id' => 9,
    'name' => 'Tinh Dầu Ngọc Lan Tây (Ylang Ylang)',
    'type' => 'Tinh Dầu Thơm Phòng',
    'cat'  => 'td_phong',
    'tag'  => $CATEGORIES['td_phong'],
    'price'=> 95000,
    'desc' => 'Hương hoa ngọt ngào, quyến rũ',
    'status' => 'Đang bán',
    'size' => '10ml',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/ngoc-lan.png',
  ],
  [
    'id' => 10,
    'name' => 'Nến Trụ Trơn Basic (Không mùi)',
    'type' => 'Nến Trang Trí',
    'cat'  => 'nen_trang_tri',
    'tag'  => $CATEGORIES['nen_trang_tri'],
    'price'=> 50000,
    'desc' => 'Nến trụ trắng dùng cho bữa tối lãng mạn hoặc trang trí',
    'status' => 'Đang bán',
    'size' => '1 cây',
    'burn' => '6–10 giờ',
      'image' => '/thongdong/assets/img/products/basic.png',
  ],
  [
    'id' => 11,
    'name' => 'Nến Bubble Cube (Nến khối lập phương)',
    'type' => 'Nến Trang Trí',
    'cat'  => 'nen_trang_tri',
    'tag'  => $CATEGORIES['nen_trang_tri'],
    'price'=> 75000,
    'desc' => 'Nến tạo hình khối bong bóng trendy, màu pastel',
    'status' => 'Đang bán',
    'size' => '1 cái',
    'burn' => '6–8 giờ',
      'image' => '/thongdong/assets/img/products/bubble-cube.png',
  ],
  [
    'id' => 12,
    'name' => 'Bộ Que Khuếch Tán Hương Biển',
    'type' => 'Que Khuếch Tán Tinh Dầu',
    'cat'  => 'que_khuech_tan',
    'tag'  => $CATEGORIES['que_khuech_tan'],
    'price'=> 220000,
    'desc' => 'Lọ thủy tinh và que mây, hương gió biển tươi mát',
    'status' => 'Đang bán',
    'size' => '100ml',
    'burn' => '3–5 tuần (tuỳ môi trường)',
      'image' => '/thongdong/assets/img/products/bo-que.png',
  ],
  [
    'id' => 13,
    'name' => 'Máy Xông Tinh Dầu Vân Gỗ',
    'type' => 'Máy Khuếch Tán Tinh Dầu',
    'cat'  => 'may_khuech_tan',
    'tag'  => $CATEGORIES['may_khuech_tan'],
    'price'=> 350000,
    'desc' => 'Máy phun sương siêu âm, đèn LED đổi màu, vỏ vân gỗ',
    'status' => 'Đang bán',
    'size' => '1 máy',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/may-xong.png',
  ],
  [
    'id' => 14,
    'name' => 'Tinh Dầu Treo Xe Cà Phê',
    'type' => 'Tinh Dầu Treo',
    'cat'  => 'td_treo',
    'tag'  => $CATEGORIES['td_treo'],
    'price'=> 65000,
    'desc' => 'Khử mùi xe ô tô, hương cà phê rang xay tỉnh táo',
    'status' => 'Đang bán',
    'size' => '8–10ml',
    'burn' => '2–4 tuần',
      'image' => '/thongdong/assets/img/products/ca-phe.png',
  ],
  [
    'id' => 15,
    'name' => 'Kéo Cắt Bấc Nến (Wick Trimmer)',
    'type' => 'Phụ kiện nến',
    'cat'  => 'phu_kien',
    'tag'  => $CATEGORIES['phu_kien'],
    'price'=> 110000,
    'desc' => 'Kéo chuyên dụng cắt bấc nến để tránh khói đen',
    'status' => 'Đang bán',
    'size' => '1 cái',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/keo.png',
  ],
  [
    'id' => 16,
    'name' => 'Đèn Đốt Nến Thơm (Candle Warmer)',
    'type' => 'Phụ kiện nến',
    'cat'  => 'phu_kien',
    'tag'  => $CATEGORIES['phu_kien'],
    'price'=> 450000,
    'desc' => 'Đèn halogen làm chảy nến không cần đốt lửa, an toàn',
    'status' => 'Đang bán',
    'size' => '1 cái',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/den.png',
  ],
  [
    'id' => 17,
    'name' => 'Set Quà "Self-Love" (Cho Nàng)',
    'type' => 'Set quà tặng',
    'cat'  => 'set_qua',
    'tag'  => $CATEGORIES['set_qua'],
    'price'=> 390000,
    'desc' => 'Gồm 1 nến hoa hồng, 1 muối tắm và thiệp',
    'status' => 'Đang bán',
    'size' => 'Set',
    'burn' => '—',
      'image' => '/thongdong/assets/img/products/18.png',
  ],
  [
    'id' => 18,
    'name' => 'Nến Thơm Mùa Lễ Hội "Gingerbread"',
    'type' => 'Bộ sưu tập mùa Lễ Hội',
    'cat'  => 'le_hoi',
    'tag'  => $CATEGORIES['le_hoi'],
    'price'=> 200000,
    'desc' => 'Hương bánh quy gừng và quế ấm áp cho Giáng Sinh',
    'status' => 'Ngừng bán',
    'size' => '220g',
    'burn' => '35–40 giờ',
      'image' => '/thongdong/assets/img/products/ginger.png',
  ],
];

